defmodule Volapi.Message.Config do
  defstruct [
    cdn_domain: "",
    chat_max_alias_length: 12,
    chat_max_history: 300,
    chat_max_message_length: 300,
    checksum2: "",
    created_time: 0,
    dmca_mail: "",
    download_cookie_lifetime: 259200,
    file_max_size: 21474840000,
    file_time_to_live: 0,
    max_ban_message_length: 500,
    max_concurrent_uploads: 1,
    max_custom_room_id_length: 20,
    max_report_text_length: 1000,
    max_room_name_length: 27,
    name: "",
    owner: "",
    private: true,
    pro_reward_min_room_age: 604800000,
    room_disabled_redirect_timeout: 3600,
    round_up_threshold: 0.2,
    session_lifetime: 604800,
    site: "",
    sitename: "",
    title_append: "",
    ui_enable_gallery: true,
    ui_gallery_buttons_hide_timeout: 2000,
    ui_gallery_honor_filter: true,
    ui_gallery_title_hide_timeout: 2000,
    ui_tooltip_show_delay: 150,
    room: "",
  ]
end
